
server:
  port: 9004

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/

feign:
ReadTimeout: 100000
  ConnectTimeout: 100000 
  MaxAutoRetries: 0
  hystrix:
    enabled: false
