server:
  port: 5010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: auth-db
feign:
ReadTimeout: 100000
  ConnectTimeout: 100000 
 ` MaxAutoRetries: 1
 hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
